GET http://localhost:5000/api/equipment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJuYW1lIjoiYWJjMyJ9LCJpYXQiOjE2NjYyNjE3MTMsImV4cCI6MTY2NjI2MjMxM30.Yqxp9hkz5Bj6X-sJZHfIRH0qf7mfeBa4RvCPot9ghBs

###
GET http://localhost:5000/api/equipment/6350fc9619b2ec6783f7f160
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJuYW1lIjoiYWJjMyJ9LCJpYXQiOjE2NjYyNTkzMzAsImV4cCI6MTY2NjI1OTkzMH0.7ksLc8LHFnE1xTWo5u5LYAm07msVtRIyc0fhxSWL1Ak

###
GET http://localhost:5000/api/equipment/getByUser/null
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJuYW1lIjoiYWJjMyJ9LCJpYXQiOjE2NjYyNTkzMzAsImV4cCI6MTY2NjI1OTkzMH0.7ksLc8LHFnE1xTWo5u5LYAm07msVtRIyc0fhxSWL1Ak


###
POST http://localhost:5000/api/equipment/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJuYW1lIjoiYWJjMyJ9LCJpYXQiOjE2NjYyNTMyMDcsImV4cCI6MTY2NjI1MzgwN30.AlZEB65VMig2xKuoyvy2BPcRAlYC3HhM5LMfM66a3vA


{
  "name": "23LCD4038",
  "type": "monitor",
  "status": "empty"
}

###
PUT http://localhost:5000/api/equipment/635102135aea2c48753fadea
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJuYW1lIjoiYWJjMyJ9LCJpYXQiOjE2NjYyNjE3MTMsImV4cCI6MTY2NjI2MjMxM30.Yqxp9hkz5Bj6X-sJZHfIRH0qf7mfeBa4RvCPot9ghBs

{
  "user":"abc2"
}
###
DELETE http://localhost:5000/api/equipment/6350fcd83e4f78942c204231
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJuYW1lIjoiYWJjMyJ9LCJpYXQiOjE2NjYyNTI5OTMsImV4cCI6MTY2NjI1MzU5M30.H-ZG190OTznBxbPHU2W84_hfEV_mViNVcGZqym5heSY


