GET http://localhost:5000/api/users/profile
Content-Type: application/json
x_authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJuYW1lIjoiYWJjMyJ9LCJpYXQiOjE2NjYyMzgxMjMsImV4cCI6MTY2NjIzODcyM30.QtY74geJNMIV96ynDyNMSrOFCas-by_mI0rZx6_YrmY
