GET http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJuYW1lIjoiYWJjMyJ9LCJpYXQiOjE2NjYzMjExMzAsImV4cCI6MTY2NjMyMTczMH0.35KREu_2RR6Q169maK1UKDmoQRMGUKdUPt1C5bGKZIE