###
GET  http://localhost:5000/api/role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJuYW1lIjoiYWJjNCJ9LCJpYXQiOjE2NjgwNjUyOTgsImV4cCI6MTY2ODA2NjE5OH0.KLVOSW96ghuFhauq4yUe1FMTJwQRyVC-KxbkzVCKmMo

###
GET  http://localhost:5000/api/role/user1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJuYW1lIjoiYWJjNCJ9LCJpYXQiOjE2NjgwNjUyOTgsImV4cCI6MTY2ODA2NjE5OH0.KLVOSW96ghuFhauq4yUe1FMTJwQRyVC-KxbkzVCKmMo

###
POST http://localhost:5000/api/role/create
Content-Type: application/json


{
  "keyword":"manager",
  "name":"Manager Role"
}


###
PUT http://localhost:5000/api/role/user
Content-Type: application/json


{
  "keyword":"user",
  "name":"User Role"
}

###
DELETE http://localhost:5000/api/role/user
Content-Type: application/json


